# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=40)),
                ('g_price', models.IntegerField()),
                ('g_collection', models.ManyToManyField(to='app.User')),
            ],
        ),
    ]
