# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['s_score']},
        ),
        migrations.AddField(
            model_name='student',
            name='s_english',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='s_math',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='s_test',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
