# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190226_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
